disabled_rules: # rule identifiers to exclude from running
  - comma
  - control_statement
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - compiler_protocol_init
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_hashing
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - nsobject_prefer_isequal
  - opening_brace
  - operator_whitespace
  - orphaned_doc_comment
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - shorthand_operator
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_semicolon
  - type_body_length
  - unneeded_break_in_switch
  - unused_capture_list
  - unused_control_flow_label
  - unused_enumerated
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - weak_delegate
  - xctfail_message

# opt_in_rules:
#   - closure_spacing
#   - operator_usage_whitespace
#   - force_unwrapping
#   - fatal_error_message
#   - sorted_imports

 excluded:
   - Pods  # exclude pods directory from linting.

cyclomatic_complexity:
    ignores_case_statements: true
    warning: 10
    error: 20
    
trailing_whitespace:
    ignores_empty_lines: true
    ignores_comments: true
        

reporter: "json" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
