# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do |options|

  lane :danger_run do |options|

   puts "token = #{ENV["DANGER_GITHUB_API_TOKEN"]}"

    danger(
      danger_id: options[:danger_id],
      dangerfile: "Dangerfile",
      github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
      verbose: true,
      fail_on_errors: true,
      use_bundle_exec: true
    )
  end 

  lane :build do
    scan(
      project: "WebService.xcodeproj",
      scheme: "WebService"
    ) 
  end 
  
end
