name: CI

on: pull_request 

jobs:
  danger_run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Danger Run
      env:
        token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: |
        bundle install
        sh ./scripts/configure-shell-env.sh
        bundle exec fastlane danger_run danger_id:"code_analysis" token:"$token"


  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Build project
      run:  |
        bundle install
        bundle exec fastlane build

