name: CI

on: pull_request 

jobs:
  danger_run:
    runs-on: macOS-latest
    steps:
      uses: actions/checkout@master
      name: Danger Run
      run: |

  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build project
      run:  |
        bundle install
        bundle exec fastlane danger_run

