name: CI

on: pull_request 

jobs:
  Code_Analysis:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Code Analysis
      env:
        token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: |
        bundle install
        bundle exec fastlane danger_run danger_id:"code_analysis" token:"$token"


  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Build project
      run:  |
        bundle install
        bundle exec fastlane build

